In [1]:
import itertools
import pickle
import math

import lightgbm
import numpy as np
import pandas as pd
import shap
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeRegressor, plot_tree
import sklearn.ensemble

In [2]:
from sklearn.ensemble import RandomForestClassifier

In [3]:
import lightgbm
import shap

data = sklearn.datasets.load_iris(as_frame=True)

df = data["frame"].sample(100, random_state=123).reset_index(drop=True)

X, y = df.drop(columns="target"), df["target"]

model = RandomForestClassifier(
).fit(X, y)

# explainer = shap.TreeExplainer(model, data=X)
explainer = shap.TreeExplainer(model)

shap_values = explainer.shap_values(X)

print(df.target.value_counts(normalize=True).sort_index().values)
print(np.exp(explainer.expected_value))
print(explainer.expected_value)

going through node_sample_weight branchg
[0.38 0.28 0.34]
[1.46667803 1.325116   1.39863953]
[0.383  0.2815 0.3355]
