* [`~`](https://docs.python.org/3.7/reference/expressions.html#unary-arithmetic-and-bitwise-operations): bitwise not, for python integer x, it’s essentially calculates -x - 1
* [`np.logical_not`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.logical_not.html#numpy-logical-not): logical NOT
* `-`: minus

In [3]:
import numpy as np

# <font color='red'>`~` doesn't work as expected for Python Boolean values</font>, since they're aint under the hood

In [18]:
~True

-2

In [19]:
~False

-1

In [22]:
1 - True

0

In [23]:
1 - False

1

# Experiment with boolean

In [4]:
a1 = np.array([True, False])

In [16]:
a1.dtype

dtype('bool')

In [5]:
a1

array([ True, False])

In [6]:
~a1

array([False,  True])

In [7]:
np.logical_not(a1)

array([False,  True])

In [8]:
-a1

TypeError: The numpy boolean negative, the `-` operator, is not supported, use the `~` operator or the logical_not function instead.

# Experiment with numpy int

In [10]:
a2 = np.array([0, 1, 2, True, False])

In [17]:
a2.dtype

dtype('int64')

In [11]:
a2

array([0, 1, 2, 1, 0])

In [12]:
~a2

array([-1, -2, -3, -2, -1])

In [13]:
np.logical_not(a2)

array([ True, False, False, False,  True])

In [14]:
-a2

array([ 0, -1, -2, -1,  0])