We focus on the case in 3D.

In [1]:
import numpy as np
import sympy as sp

## Data points only span a line

In [2]:
X = np.array(
    [
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [2, 4, 6, 8],
    ]
)

In [3]:
X

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [2, 4, 6, 8]])

In [4]:
μ = X.mean(axis=1, keepdims=True)

In [5]:
μ

array([[2.5],
       [2.5],
       [5. ]])

In [6]:
cov = ((X - μ) @ (X - μ).T) / (X.shape[1] - 1)
cov

array([[1.66666667, 1.66666667, 3.33333333],
       [1.66666667, 1.66666667, 3.33333333],
       [3.33333333, 3.33333333, 6.66666667]])

In [7]:
np.cov(X)

array([[1.66666667, 1.66666667, 3.33333333],
       [1.66666667, 1.66666667, 3.33333333],
       [3.33333333, 3.33333333, 6.66666667]])

In [8]:
assert ((cov - np.cov(X)) < 1e-8).all()

In [9]:
sp.Matrix(cov).eigenvals()

{1.13524436206067e-64: 1, 1.08440425413799e-63: 1, 10.0000000000000: 1}

## Data points only span a plane

In [10]:
X = np.array(
    [
        [1, 1, 2, 3],
        [1, 3, 4, 5],
        [2, 1, 3, 5],
    ]
)

In [11]:
X

array([[1, 1, 2, 3],
       [1, 3, 4, 5],
       [2, 1, 3, 5]])

In [12]:
μ = X.mean(axis=1, keepdims=True)

In [13]:
μ

array([[1.75],
       [3.25],
       [2.75]])

In [14]:
cov = ((X - μ) @ (X - μ).T) / (X.shape[1] - 1)
cov

array([[0.91666667, 1.41666667, 1.58333333],
       [1.41666667, 2.91666667, 2.08333333],
       [1.58333333, 2.08333333, 2.91666667]])

In [15]:
np.cov(X)

array([[0.91666667, 1.41666667, 1.58333333],
       [1.41666667, 2.91666667, 2.08333333],
       [1.58333333, 2.08333333, 2.91666667]])

In [16]:
assert ((cov - np.cov(X)) < 1e-8).all()

In [17]:
sp.Matrix(cov).eigenvals()

{5.90296855201959: 1, -1.11022302462516e-17: 1, 0.847031447980414: 1}

So

**Given $N$ data points of $D$ dimension, when the dimension of the span of the data points is less than $D$, then the covariance matrix is positive-semidefinite as you'll be able to find a vector that is orthogonal to all data point vectors. Equivalently, at least one eigenvalues of the covariance matrix is 0.**